language: cpp
matrix:
  include:
    - compiler: gcc-5
      os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
      env: CXX=g++-5
      env: CC=gcc-5
      env: GCCPATH=/usr/bin/gcc-5
      env: GPPPATH=/usr/bin/g++-5
    - compiler: gcc-6
      os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6 
            - libboost-all-dev
      env: CXX=g++-6
      env: CC=gcc-6
      env: GCCPATH=/usr/bin/gcc-6
      env: GPPPATH=/usr/bin/g++-6
    - compiler: clang-3.7
      os: linux
      sudo: required
      dist: trusty    
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages:
            - clang-3.7
            - libboost-all-dev
      env: CXX=clang++-3.7
      env: CC=clang++-3.7
      env: LINK=clang++-3.7
    - compiler: clang
      os: osx
      env: CXX=clang++
      env: CC=clang
      env: LINK=clang++
script:
  - cd src
  - make -j2
